config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
    resources :balance_managements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance_management.rb
class BalanceManagement < ApplicationRecord
  #belongs_to :category
end

app/models/concerns/balance_management.rb
class BalanceManagement < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/balance_managements_controller.rb
class BalanceManagementsController < ApplicationController
    def index
        @balance_managements = BalanceManagement.all
    end

    def show
        @balance_management = BalanceManagement.find(params[:id])
    end

    def new
        @balance_management = BalanceManagement.new
    end

    def create
        @balance_management = BalanceManagement.new(balance_management_params)
        @balance_management.category_id = 1
        @balance_management.save
        redirect_to balance_managements_url
    end

    def edit
        binding.pry
        @balance_management = BalanceManagement.find(params[:id])
    end

    def update
        @balance_management = BalanceManagement.find(params[:id])
        @balance_management.update(balance_management_params)
        redirect_to balance_management_url @balance_management
    end

    def destroy
        @balance_management = BalanceManagement.find(params[:id])
        @balance_management.destroy
        redirect_to balance_managements_url
    end
    
 private
    def balance_management_params
      params.require(:balance_management).permit(:name, :description, :price)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #  super
  # end

  # PUT /resource
    def update
      super
    end

  # DELETE /resource
  # def destroy
  #   super
  # end

   def verify
   end
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

    protected

  # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(
        :sign_up, keys: [ :name, :postal_code, :address, :phone, :email, :password, :password_confirmation ])
    end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(
      :account_update, keys: [ :name, :postal_code, :address, :phone, :email, :password, :password_confirmation ])
  end
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
    verify_path
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
    before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end
  
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(user)
    balance_managements_path
  end

  def after_sign_out_path_for(user)
    root_path
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(
      :sign_in, keys: [ :name, :postal_code, :address, :phone, :email, :password, :password_confirmation ])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/balance_managements/edit.html.erb
<h1>家計簿</h1>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<%= form_with model: @balance_management, url: balance_management_path, method: :put do |f| %>
  <h3>金額</h3>
  <%= f.number_field :price %>
  <h3>商品名やお店の名前</h3>
  <%= f.text_field :name %>
  <h3>メモ</h3>
  <%= f.text_area :description %>
  <%= f.submit "Edit" %>
  <button type="button" class="btn btn-info">作成</button>
<% end %>

<%= link_to "Back", balance_managements_path %>

app/views/balance_managements/index.html.erb
<h1>Products#index</h1>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<% @balance_managements.each do |balance_management| %>
  <%= balance_management.name %>
  <%= balance_management.description %>
  <%= balance_management.price %>
  <%= link_to "Show", balance_management_path(balance_management) %>
  <%= link_to "Edit", edit_balance_management_path(balance_management) %>
  <%= link_to 'Delete', balance_management_path(balance_management), method: :delete, data: { confirm: 'Are you sure?' }  %>
<% end %>

<%= link_to "New", new_balance_management_path %>
<button type="button" class="btn btn-info">NEW</button>

app/views/balance_managements/new.html.erb
<h1>家計簿</h1>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<%= form_with model: @balance_management, url: balance_managements_path do |f| %>
  <h3>金額</h3>
  <%= f.number_field :price %>
  <h3>商品名やお店の名前</h3>
  <%= f.text_field :name %>
  <h3>メモ</h3>
  <%= f.text_area :description %>
  <%= f.submit "Create" %>
  <button type="button" class="btn btn-info">作成</button>
<% end %>

<%= link_to "Back", balance_managements_path %>

app/views/balance_managements/show.html.erb
<h1>Products#show</h1>
<%= @balance_management.name %>
<%= @balance_management.description %>
<%= @balance_management.price %>

<%= link_to "Back", balance_managements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
          <a class="navbar-brand" href="/">ikon</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <!-- Right Side Of Navbar -->
              <ul class="navbar-nav ml-auto">
              <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
              <% if user_signed_in? %>
                <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
                <li class="nav-item dropdown">
                  <%= link_to "#", id: "navbarDropdown", class: "nav-link dropdown-toggle",
                  role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } do %>
                      <%= current_user.name %> <span class="caret"></span>
                  <% end %>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to "ログアウト", "#", class: "dropdown-item", action: logout_path,
                    onclick: "event.preventDefault(); document.getElementById('logout-form').submit();" %>

                      <%= form_with url: logout_url, method: "get", id: "logout-form" do |f| %>
                      <%= f.submit style: "display: none;"%>
                    <% end %>

                    <%= form_with url: logout_url, method: "get", id: "logout-form" do |f| %>
                      <%= f.submit style: "display: none;"%>
                    <% end %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "登録", new_user_registration_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="py-4 mb-5">
      <% if notice %><p class="alert alert-warning"><%= notice %></div><% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>